// Generated by the capnpc-swift plugin to the Cap'n Proto schema compiler.
// DO NOT EDIT.
// source: Resources/schema.capnp

public struct Node {
internal var storage: Storage
public struct Field {
internal var storage: Storage
public struct Enumerant {
internal var storage: Storage
public struct Superclass {
internal var storage: Storage
public struct Method {
internal var storage: Storage
public struct Type {
internal var storage: Storage
public struct Brand {
internal var storage: Storage
public struct Value {
internal var storage: Storage
public struct Annotation {
internal var storage: Storage
public struct CodeGeneratorRequest {
internal var storage: Storage
